spring:
  datasource:
    url: jdbc:oracle:thin:@oracle.fiap.com.br:1521:ORCL
    username: pf1646
    password: fiap23
  jpa:
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: create
